version: '3.6'

services:

  mongo:
    image: mongo
    restart: always
    networks:
      - mongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: blog
    ports:
      - 27017:27017
    volumes:
      # - ./data:/data/db
      - ./initdb:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    networks:
      - mongoDB
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456

networks:
  mongoDB:
    driver: bridge
